name: Definitely not desktop build

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      sdk_branch:
        description: "Custom SDK branch"
        required: false
        type: string

defaults:
  run:
    shell: bash

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-22.04
    steps:
      - name: Echo hello word
        id: echo-hello-world
        run: |
          echo "hello world"
